// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-76toIhMmXSz74B7CcoAruUmyQzB4gc',
    appId: '1:831777599075:web:adfb2b52abb46c340d1256',
    messagingSenderId: '831777599075',
    projectId: 'orbital-signal-369106',
    authDomain: 'orbital-signal-369106.firebaseapp.com',
    databaseURL: 'https://orbital-signal-369106-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbital-signal-369106.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC64zvcOfOD-S8AfznjFm-5tlIhdDvBCrY',
    appId: '1:831777599075:android:7c4bcce0053710270d1256',
    messagingSenderId: '831777599075',
    projectId: 'orbital-signal-369106',
    databaseURL: 'https://orbital-signal-369106-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbital-signal-369106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTWOlMKgyqFQysfhUtV60Jjw6gqnPlAw',
    appId: '1:831777599075:ios:1822f47918f5641b0d1256',
    messagingSenderId: '831777599075',
    projectId: 'orbital-signal-369106',
    databaseURL: 'https://orbital-signal-369106-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbital-signal-369106.firebasestorage.app',
    androidClientId: '831777599075-b719d65ruo32rbk1vnomgpcvmpdge012.apps.googleusercontent.com',
    iosClientId: '831777599075-chaukt3loh9ks7ir6ua0dt20amsjq185.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothstoreAdminPannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTWOlMKgyqFQysfhUtV60Jjw6gqnPlAw',
    appId: '1:831777599075:ios:1822f47918f5641b0d1256',
    messagingSenderId: '831777599075',
    projectId: 'orbital-signal-369106',
    databaseURL: 'https://orbital-signal-369106-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbital-signal-369106.firebasestorage.app',
    androidClientId: '831777599075-b719d65ruo32rbk1vnomgpcvmpdge012.apps.googleusercontent.com',
    iosClientId: '831777599075-chaukt3loh9ks7ir6ua0dt20amsjq185.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothstoreAdminPannel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj-76toIhMmXSz74B7CcoAruUmyQzB4gc',
    appId: '1:831777599075:web:98cba3883f67c4a80d1256',
    messagingSenderId: '831777599075',
    projectId: 'orbital-signal-369106',
    authDomain: 'orbital-signal-369106.firebaseapp.com',
    databaseURL: 'https://orbital-signal-369106-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbital-signal-369106.firebasestorage.app',
  );
}
