import 'package:cloud_firestore/cloud_firestore.dart';

class AutoGeneratedUID {
  Future<String> getAutogeneratedUIDForCategories() async {
    DocumentReference catDoc = FirebaseFirestore.instance.collection('categories').doc();
    return catDoc.id;
  }

  Future<String> getAutogeneratedUIDForProduct() async {
    DocumentReference productDoc = FirebaseFirestore.instance.collection('products').doc();
    return productDoc.id;
  }
}
